/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125365-g9a01c1cb6a-20260630"
#endif /* AVUTIL_FFVERSION_H */
